### ISSUE TITLE
说到底，就是你们这帮傻逼，才导致我们上不了外网

### ISSUE THREAD

**Issue by escX** [zhaohmng/-21-#113]
挥起民主自由的大棒，搞乱中东非洲苏联，又想来这里搞事，滚吧。

**Comment by dy-huang** [comment]
骂的好,这种傻逼少一点,当初也不会墙起来.当初就是在外网四处都是这些轮子发这种玩意

**Comment by yingjiayu** [comment]
说的对，轮子这群人想通过舆论手段影响中国发展，简直痴心妄想，老美再怎么支持你们也吠不了几声了
