### ISSUE TITLE
都骂的好凶，文革批斗的既视感

### ISSUE THREAD

**Issue by WPolly** [zhaohmng/-21-#45]
看来都知道妄议中央的下场不会好，伟光正如宗教一般

**Comment by Deep-Digger** [comment]
你可算了吧，这篇文章怕是小学语文写出来的，充斥着妄想和阴谋论，真的是搞笑

**Comment by WPolly** [comment]
就妄议了又怎样？需要赶尽杀绝？不就是怕ccp的淫威嘛

**Comment by hongliyuyulvliyuyulv** [comment]
孩子，你的思想已被毒害了。爸爸爱你呦！

**Comment by Deep-Digger** [comment]
我觉得你要么是心智不成熟要么是生活在国外一直在接受充满偏见和谣言的新闻的毒害，睁眼看看吧，现在中国大陆没你想象的那么不堪，大家生活的都很好都在进步，也不会受到所谓的政治迫害，大陆的人看这种文章都跟看笑话一样，谁当真谁输了，我跟你说这些感觉都在浪费口舌

**Comment by lfkbb** [comment]
我发现你挺活跃啊，还是一直在支持傻逼言论

**Comment by WPolly** [comment]
> 我觉得你要么是心智不成熟要么是生活在国外一直在接受充满偏见和谣言的新闻的毒害，睁眼看看吧，现在中国大陆没你想象的那么不堪，大家生活的都很好都在进步，也不会受到所谓的政治迫害，大陆的人看这种文章都跟看笑话一样，谁当真谁输了，我跟你说这些感觉都在浪费口舌

大陆的你有新闻自由吗，有言论自由吗，除了歌功颂德你还能看到什么，中南海发生什么事情能有任何机构或媒体监督？你能看到全貌？还不是想让你看什么你才能看到什么，你敢说不是党管一切，你敢说不是权大于法，你敢说没有权贵阶层凌驾于法律之上？

**Comment by WPolly** [comment]
> 孩子，你的思想已被毒害了。爸爸爱你呦！

小粉红的幼稚话语，真可笑，还思想毒害，我靠，你回到文革去吧

**Comment by WPolly** [comment]
> 我发现你挺活跃啊，还是一直在支持傻逼言论

一口一个别人傻逼，希望你是真聪明

**Comment by Deep-Digger** [comment]
哎，我觉得您应该是早年移居美国或者其他地方的人。我还是希望能多点了解和交流，少点互骂。包括对您和对他们也是。您如果很多年没回来过了，不妨回来看看，这里在发展，是有不足，也有腐败，但是大家都在努力改正。至于您说的新闻自由什么的，如果您真的相信什么自由都没有，其实是您被洗脑了，这个也不怪你。大陆到现在已经够了解世界了，但是世界还不了解中国，你的误解就是长期以来的片面的报道和新闻误导的结果，少些意识形态的对立，多些了解与沟通。至于那些什么党管一切，都是几十年之前的事了。言尽于此，勿回复。

**Comment by WPolly** [comment]
说起话来都是赵家人的口吻，由衷的骄傲和自豪，我替共产党感到高兴，希望年青一代都有这种觉悟。

**Comment by Celint** [comment]
WPolly 你怕不是个宝器！我们当然有新闻自由，而且我们还会筛选真的新闻，不像你们，什么HK is bracing 。。。。This is extremely dangerous to our democracy！你们是复读机吗？说我们没有新闻自由，结果你们假新闻满天飞！改一下词会死啊！
我们有言论自由，而且我们讲实事求是，不像你们，假话满天飞，这篇文章有那一句话是真的你告诉我？？？什么小学文化愚且蠢的😡我都不想说了。
我本来想指望你这里能说出一点真相，哪怕一点都好，不然也不会被我们中国的网友们看不起，结果，你有那一句话是真的？？？
中南海发生什么事情能有任何机构或媒体监督？那你又是怎么知道的，自相矛盾！你的每一句话我都能找出至少3句话反驳，而且都有证据！！！
你说的每一句话但凡是有一点点证据，我都不会如此反感你了！！
什么煞笔玩意！

**Comment by anuoua** [comment]
@WPolly  骂共产党骂的好凶，文革批斗的既视感。
