### ISSUE TITLE
程序员的素质可见一斑！

### ISSUE THREAD

**Issue by WPolly** [zhaohmng/-21-#59]
人家在自己的仓库议论了下中南海，就让政治正确的程序员如丧考妣，污言秽语，恶毒咒骂，真恶心！

**Comment by YorokobiMaster** [comment]
您说什么呢，没看到24 days ago注册？政治正确什么呢，不要乱开地图炮哦~

**Comment by WPolly** [comment]
24 days ago 注册又说明什么，这就是可以随意辱骂，乱棍打死的理由？

**Comment by UserFarmer** [comment]
曾经GitHub面临和其他很多网站一样的命运，是在李开复老师和众多业界大佬共同发声支援下，我们才能继续正常使用，请不要在这里讨论政治，使他们的努力付之东流。

**Comment by WPolly** [comment]
我也不赞成在这里讨论政治，但没必要恶毒咒骂，还好大多数程序员能fq

**Comment by 2788** [comment]
我觉得这个人的政治立场像个汉奸

**Comment by lfkbb** [comment]
你怎么这么像孤儿呢？？你怕不是哪个石头缝里蹦出来的？？？

**Comment by zerofancy** [comment]
> 人家在自己的仓库议论了下中南海，就让政治正确的程序员如丧考妣，污言秽语，恶毒咒骂，真恶心！

github举报功能不好用，我又觉得他恶心到了我，那只能骂他解解气了啊

**Comment by YorokobiMaster** [comment]
忙着洗白真恶心

**Comment by Celint** [comment]
他在仓库里讨论政治我们是管不着，但是我们不说话吧，你又说我们没有言论自由。我们说话吧，想讨论一番，但是一看，特么没有一句话是真的，恶心到我们了懂不？你们特么的言论自由就是乱说话不负责任，你凡是说什么东西都要讲证据的好不好？？没有证据就乱评论政治，这不是诋毁是什么？？既然他可以不负责任诋毁人，那我们凭什么不能骂他？我劝你们多读点书，再来上网，不要老是那一套皿煮滋油，看多了也烦的。

**Comment by 1562536816** [comment]
> 人家在自己的仓库议论了下中南海，就让政治正确的程序员如丧考妣，污言秽语，恶毒咒骂，真恶心！

你怕是个傻子吧，这是什么地方？别人无缘无故发这种政治言论还要要求对他好点？素质是对人讲的，不是对狗，譬如你这样所谓打着言论自由的弱智，你这么崇尚言论自由你去美国搞搞独立给大家表演一下什么叫做言论自由，不敢就别出来装你妈的白莲花。

**Comment by Fu-LianPeng** [comment]
同意，最恶毒的人莫过于挑拨民族分裂的人，挑起民族争端的人，要求一个稳定向好的社会大变革的人，七十年前我们的先辈用多少的人命，换来这么不容易的好的环境，他的一句话倒是简单，人命却如草芥一般。最爱挑起别人名族争斗的人非usa莫属了，我是说政府他们的恶毒之处，不是所有人。

**Comment by WPolly** [comment]
> > 人家在自己的仓库议论了下中南海，就让政治正确的程序员如丧考妣，污言秽语，恶毒咒骂，真恶心！
> 
> 你怕是个傻子吧，这是什么地方？别人无缘无故发这种政治言论还要要求对他好点？素质是对人讲的，不是对狗，譬如你这样所谓打着言论自由的弱智，你这么崇尚言论自由你去美国搞搞独立给大家表演一下什么叫做言论自由，不敢就别出来装你妈的白莲花。

程序员中的义和团红卫兵不少啊，别说别人你更是脑残，休再放屁，时间会告诉你真相。

**Comment by Celint** [comment]
哟，这么喜欢给别人扣帽子啊。那我反问一下：你又是从那个地底缝里跑出来的曱甴，还是恨国蛆？

**Comment by sunalbert** [comment]
你是个憨批吗？汉奸走狗

**Comment by shenyuequn** [comment]
你死了应该都看不到时间给你的真相。废物。

**Comment by WPolly** [comment]
> 你死了应该都看不到时间给你的真相。废物。

我操死你妈，你个蠢逼

**Comment by WPolly** [comment]
> 哟，这么喜欢给别人扣帽子啊。那我反问一下：你又是从哪个地底缝里跑出来的曱甴，还是恨国蛆？

恨你马勒戈壁

**Comment by WPolly** [comment]
> 你是个憨批吗？汉奸走狗

奸你妈，奸你妹，奸你全家

**Comment by zuichoudiyi** [comment]
@WPolly 我一拳就能把你从这打到五郎勾 你不是爱吃屎吗 那里的屎多的很 我也算是帮你了呀

**Comment by zuichoudiyi** [comment]
@WPolly 你的妓女🐴明天必死，废物弟弟你必死全家
五行缺日命中欠操的几把玩意
你鼻子下面是牛欢喜啊，请你不要用你的欢愉器官对我说话，这是很不礼貌的，谢谢你的合作。我能理解你的难受，毕竟万里长城永不倒，你的烂嘴要人搞
你婊妈野爹们挨个用鼻孔互相相位猛冲鼻子进眼眶子出人均五官均为屁眼
你妈关注果子狸7777妖妖写字楼大妈，你爸特别关注理想记，你在微博上为我的英雄学院打call洗地，你弟是个二刺螈满嘴抽象话，你们都有光明的未来。
本野爹用雷神之锤汇聚众神之力一锤你🐴的子宫把你捶成了脑残才导致你一生出来就是个废物
你婊子妈被我开着装甲车碾压成滩烂泥后竟然意外组成了一幅精美无比的迷宫图

**Comment by zuichoudiyi** [comment]
@WPolly 我日你妈了个狗逼一条鹅毛特么的就能把你那傻逼一样的马眼操的疯狂表水，玛德你自己嗨吧几把剁下来为自己吃香肠，你妈还在一边特么的跟你爸玩针线活
你妈死了！你妈被原子弹炸的宫缩！宫缩以后！得知自己患上子宫肌瘤！需要立即切除！否则全身会被月经的烂血腐蚀而死！ 
那位大爷上茅厕拉的屎你妈全部接着吃了，你妈犹兴未尽又继续把那位大爷的屁股全舔干净了，那位大爷要走了你妈不让，非让那位大爷在你妈嘴里又撒了一泡尿才让大爷离开，那位大爷很高兴的说自从有了你妈他上厕所都不再用卫生纸了
你婊子妈子宫肌瘤过多花重金邀请我去给她治疗我就拿着一颗原子弹在她子宫里引爆
对面在亮狗牌，上面写满你妈死了。虽然说你不知道你爹到底是谁，但是架不住你能在我排一位根里中乱指认就啊能
把你妈干到脑抽筋

**Comment by zuichoudiyi** [comment]
@WPolly 我双手拳交你亲妈 把你臭妈多操出一个尿道 操你妈的 滚
你话那么多怎么不坐你妈坟头跟她慢慢说
-.-- --- ..- .-.   -- --- - .... . .-.   .... .- ...   ... ---   -- ..- -.-. ....   .-- .- - . .-. （加 密 通 讯）对应:你妈水真多
宁的父母灵能天赋极高，现在灵能飞升了
我日你妈大血逼螺旋升天，我还把你妈肠子抽出来塞进她嘴里，你也只能这个表情看着了，废物
你🐴的逼是不是粘你脸上了？要不你怎么长了一副逼样儿。
狗废 物我在你面前踹你妈臭 逼两脚却不料你下贱老母潮喷冲垮了奈何桥从此与你这可怜牲畜阴阳两隔，你彪子妈只能以恶臭潮吹滋你一脸作为遗物，声声放浪的淫叫作为临终遗言
我真想送你妈一朵花 对不起开个玩笑 我哪来的花 你哪来的妈
几分钟了屁也没憋出来？你这条土狗只能眼睁睁看着你爹无情说出你家悲惨身世不敢讲话  满脸油光在键盘前声泪俱下控诉2019低保只涨了489块

**Comment by zuichoudiyi** [comment]
@WPolly 江南北都有你婊子妈的嫖客你妈妈的卖屁股生意边际全世界而你妈妈的下体已经被联合国认定为最好的肉体
野儿子闻到了自己婊子妈子宫肌瘤的浓香终于按捺不住自己的劣根性开始疯狂意淫吃屎 你妈臭逼里被野爹做了扩阴手术成了香榭丽舍大道 现在正在上演车水马龙的卖逼哑剧呢，在月光的照耀下 你婊子妈阴道上所形成的沟壑依旧是那么出彩诱人 你废物爹终归在那晚识出了我就是当年嫖你瞎妈的蒙面神秘元凶啊~~~~~~
你妈的逼当年被天王老子用热翔灌大黑逼瞬间吸收迸发出一朵朵血花引来了屎壳郎你野爹我赶紧抽出大JB猛插小屄扩成了太平洋要不是你妈脑子吃翔还生不出你这个傻逼儿子
在天国和五名乌干达黑人同时拳交致死的亲妈都决定为你起尸鼓掌。
这边建议您早点没哦！要不然墓地涨价了可不行~
我那爱斯基摩烈性犬爱上了你妈的血逼并那它们那碗口粗的JB向里捅去殊不知你那婊子妈爽得屁滚niao流你这废物当时开怀大笑
老子一刀剁向你的尿道让你那细小的🐔8⃣️一分为二
贱畜老子把你🐴阴道捅烂，废物狗比玩意儿，日的你🐴嗷嗷叫，看你还敢在这里叫吗？快回家看看你🐴在床上嗷嗷直叫的样子，高潮不断奥，肛门和阴道都被捅穿了
我怕你爸外遇不够多 死着死着就没妈了
小孙子你可真jb闲。👴也很闲，于是把你的短小家伙嘎了油爆。我把它的两面炸至金黄，再裹上面包糠，给隔壁小孩。瞧把这孩给吓的，一把把你小🐔儿丢粪坑里了。不知道咋滴，你这🐔儿在管道里瞎jb转，结果转到一撤硕里。老八来吃粑粑，本来吃挺香的，结果看见你那玩意，哇哇的呕啊。
是不是你那风骚的狗娘一天到晚想着自慰 结果一次无聊把硫酸倒进自己的老B里结果活生生的把你亲妈的老B给烧了 你亲妈葬身火海了
因为这条骂我，你妈被爱判处终生孤寂，有感而孕生了你

**Comment by WPolly** [comment]
> @WPolly 江南北都有你婊子妈的嫖客你妈妈的卖屁股生意边际全世界而你妈妈的下体已经被联合国认定为最好的肉体
> 野儿子闻到了自己婊子妈子宫肌瘤的浓香终于按捺不住自己的劣根性开始疯狂意淫吃屎 你妈臭逼里被野爹做了扩阴手术成了香榭丽舍大道 现在正在上演车水马龙的卖逼哑剧呢，在月光的照耀下 你婊子妈阴道上所形成的沟壑依旧是那么出彩诱人 你废物爹终归在那晚识出了我就是当年嫖你瞎妈的蒙面神秘元凶啊~~~~~~
> 你妈的逼当年被天王老子用热翔灌大黑逼瞬间吸收迸发出一朵朵血花引来了屎壳郎你野爹我赶紧抽出大JB猛插小屄扩成了太平洋要不是你妈脑子吃翔还生不出你这个傻逼儿子
> 在天国和五名乌干达黑人同时拳交致死的亲妈都决定为你起尸鼓掌。
> 这边建议您早点没哦！要不然墓地涨价了可不行~
> 我那爱斯基摩烈性犬爱上了你妈的血逼并那它们那碗口粗的JB向里捅去殊不知你那婊子妈爽得屁滚niao流你这废物当时开怀大笑
> 老子一刀剁向你的尿道让你那细小的🐔8⃣️一分为二
> 贱畜老子把你🐴阴道捅烂，废物狗比玩意儿，日的你🐴嗷嗷叫，看你还敢在这里叫吗？快回家看看你🐴在床上嗷嗷直叫的样子，高潮不断奥，肛门和阴道都被捅穿了
> 我怕你爸外遇不够多 死着死着就没妈了
> 小孙子你可真jb闲。👴也很闲，于是把你的短小家伙嘎了油爆。我把它的两面炸至金黄，再裹上面包糠，给隔壁小孩。瞧把这孩给吓的，一把把你小🐔儿丢粪坑里了。不知道咋滴，你这🐔儿在管道里瞎jb转，结果转到一撤硕里。老八来吃粑粑，本来吃挺香的，结果看见你那玩意，哇哇的呕啊。
> 是不是你那风骚的狗娘一天到晚想着自慰 结果一次无聊把硫酸倒进自己的老B里结果活生生的把你亲妈的老B给烧了 你亲妈葬身火海了
> 因为这条骂我，你妈被爱判处终生孤寂，有感而孕生了你

吃屎五毛来GitHub舔你爷爷来了？你马上死无葬身之地了，呵呵

**Comment by lushuyu** [comment]
@WPolly 亲亲，这边建议您先把你🐴 杀了然后你个孤儿自己钻灵车里办个入坟头party然后我们给你吹一曲百🐦 朝凤

**Comment by lushuyu** [comment]
@WPolly 我开着你妈灵车撞到你家祖坟了？ 我一指把你废物吗G点戳爆 一记神龙摆尾踢爆你妈子宫 把你这废物的脑袋踢成隔壁贴子做的龟苓膏

**Comment by lushuyu** [comment]
@WPolly 只有一个妈，但是爹倒是不少

**Comment by lushuyu** [comment]
@WPolly 你以为你就是跨战马提缨枪了么，你可是要被插得头破血流直接进入医院进行生殖器卵保养。不要以为你在脸上涂了点劣质粉底，就可以掩盖你农民的本质。

**Comment by lushuyu** [comment]
@WPolly 我手持方天画戟在你妈逼里肆无忌惮的挥舞 最后给你妈子宫内壁留下了不可磨灭的痕迹
